# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Governorate.create(name: "Cairo")
Governorate.create(name: "Alexandria")
Governorate.create(name: "Ismailia")
Governorate.create(name: "Aswan")
Governorate.create(name: "Asyut")
Governorate.create(name: "The Aqasr")
Governorate.create(name: "Albahr Al'ahmar")
Governorate.create(name: "Albuhayra")
Governorate.create(name: "Bani Sweif")
Governorate.create(name: "Por Said")
Governorate.create(name: "South of Sinaa")
Governorate.create(name: "Giza")
Governorate.create(name: "Dakahlia")
Governorate.create(name: "Damietta")
Governorate.create(name: "Sohag")
Governorate.create(name: "Suez")
Governorate.create(name: "Alsharqia")
Governorate.create(name: "North Sinai")
Governorate.create(name: "Algharbia")
Governorate.create(name: "Fayoum")
Governorate.create(name: "Qalyubia")
Governorate.create(name: "Qana")
Governorate.create(name: "Kafr El-Sheikh")
Governorate.create(name: "Matruh")
Governorate.create(name: "Menoufia")
Governorate.create(name: "Minya")
Governorate.create(name: "Alwadi Aljadid")
