def create_diseases
   all_diseases = []
   all_diseases << Disease.new(name: "Acute Flaccid Myelitis (AFM)", contagious: true)
   all_diseases << Disease.new(name: "Alphaviruses", contagious: false)
   all_diseases << Disease.new(name: "Alzheimer's Diseases (Spanish)", contagious: true)
   all_diseases << Disease.new(name: "Arthritis", contagious: false)
   all_diseases << Disease.new(name: "Babesiois", contagious: true)
   all_diseases << Disease.new(name: "Blue-green Algae", contagious: false)
   all_diseases << Disease.new(name: "Cancer Environment", contagious: true)
   all_diseases << Disease.new(name: "Cancer - Breast", contagious: false)
   all_diseases << Disease.new(name: "Cancer - Cervical", contagious: true)
   all_diseases << Disease.new(name: "Cancer - Colon", contagious: false)
   all_diseases << Disease.new(name: "Cancer - Endometrial", contagious: true)
   all_diseases << Disease.new(name: "Cancer - Kidney", contagious: false)
   all_diseases << Disease.new(name: "Cancer - Liver", contagious: true)
   all_diseases << Disease.new(name: "Cancer - Multiple Myeloma", contagious: false)
   all_diseases << Disease.new(name: "Cancer - Ovarian", contagious: true)
   all_diseases << Disease.new(name: "Cancer - Pancreatic", contagious: false)
   all_diseases << Disease.new(name: "Cancer - Stomach", contagious: true)
   all_diseases << Disease.new(name: "Cancer - Thyroid", contagious: false)
   all_diseases << Disease.new(name: "Cancer - Uterus (Spanish)", contagious: false)
   all_diseases << Disease.new(name: "Carbon Monoxide Poisoning", contagious: true)
   all_diseases << Disease.new(name: "Celiac Disease", contagious: false)
   all_diseases << Disease.new(name: "Chancroid", contagious: true)
   all_diseases << Disease.new(name: "Chickenpox", contagious: false)
   all_diseases << Disease.new(name: "Chronic Obstructive Pulmonary Disease", contagious: true)
   all_diseases << Disease.new(name: "Conjunctivitis", contagious: false)
   all_diseases << Disease.new(name: "Crabs", contagious: true)
   all_diseases << Disease.new(name: "Cryptosporidiosis", contagious: true)
   all_diseases << Disease.new(name: "Cytomegalovirus (CMV)", contagious: false)
   all_diseases << Disease.new(name: "Congenital CMV", contagious: true)
   all_diseases << Disease.new(name: "Cardiovascular Disease", contagious: false)
   all_diseases << Disease.new(name: "Diphtheria", contagious: true)
   all_diseases << Disease.new(name: "AIDS (HIV/AIDS)", contagious: false)
   all_diseases << Disease.new(name: "Alzheimer’s Disease", contagious: true)
   all_diseases << Disease.new(name: "Asthma", contagious: false)
   all_diseases << Disease.new(name: "Bacterial Vaginosis", contagious: true)
   all_diseases << Disease.new(name: "Cancer", contagious: false)
   all_diseases << Disease.new(name: "Cancer - Bladder", contagious: true)
   all_diseases << Disease.new(name: "Cancer - Breast Exams and Mammograms", contagious: false)
   all_diseases << Disease.new(name: "Cancer - Cervical (Spanish)", contagious: true)
   all_diseases << Disease.new(name: "Cancer - Colorectal", contagious: false)
   all_diseases << Disease.new(name: "Cancer - Endometrial (Spanish)", contagious: true)
   all_diseases << Disease.new(name: "Cancer - Endometrial (Spanish)", contagious: false)
   all_diseases << Disease.new(name: "Cancer - Lung", contagious: true)
   all_diseases << Disease.new(name: "Cancer - Oral", contagious: false)
   all_diseases << Disease.new(name: "Cancer - Ovarian (Spanish)", contagious: true)
   all_diseases << Disease.new(name: "Cancer - Skin", contagious: false)
   all_diseases << Disease.new(name: "Cancer - Testicular", contagious: true)
   all_diseases << Disease.new(name: "Cancer - Uterus", contagious: false)
   all_diseases << Disease.new(name: "Carbapenem-Resistant Enterobacteriaceae (CRE)", contagious: true)
   all_diseases << Disease.new(name: "Chagas Disease", contagious: false)
   all_diseases << Disease.new(name: "Chlamydia", contagious: true)
   all_diseases << Disease.new(name: "Chronic Fatigue Syndrome", contagious: false)
   all_diseases << Disease.new(name: "Clostridium Difficile", contagious: true)
   all_diseases << Disease.new(name: "Coronavirus", contagious: false)
   all_diseases << Disease.new(name: "Creutzfeldt-Jakob Disease", contagious: true)
   all_diseases << Disease.new(name: "Creutzfeldt-Jakob Disease", contagious: false)
   all_diseases << Disease.new(name: "Depression", contagious: true)
   all_diseases << Disease.new(name: "Eastern Equine Encephalitis Virus (EEEV)", contagious: true)
   all_diseases << Disease.new(name: "Ebola Virus", contagious: true)
   all_diseases << Disease.new(name: "Enterovirus", contagious: false)
   all_diseases << Disease.new(name: "Fibromyalgia", contagious: true)
   all_diseases << Disease.new(name: "Gonorrhea", contagious: false)
   all_diseases << Disease.new(name: "Group A Streptococcus", contagious: true)
   all_diseases << Disease.new(name: "Hantaviruses", contagious: false)
   all_diseases << Disease.new(name: "Head Lice", contagious: true)
   all_diseases << Disease.new(name: "Heart Disease", contagious: false)
   all_diseases << Disease.new(name: "Helicobacter Pylori", contagious: true)
   all_diseases << Disease.new(name: "High Blood Pressure", contagious: false)
   all_diseases << Disease.new(name: "HIV/AIDS", contagious: true)
   all_diseases << Disease.new(name: "Human Papillomavirus", contagious: false)
   all_diseases << Disease.new(name: "E. Coli", contagious: true)
   all_diseases << Disease.new(name: "Ehrlichiosis", contagious: false)
   all_diseases << Disease.new(name: "Fibroids", contagious: true)
   all_diseases << Disease.new(name: "Flu", contagious: false)
   all_diseases << Disease.new(name: "Giardiasis", contagious: true)
   all_diseases << Disease.new(name: "Gout", contagious: false)
   all_diseases << Disease.new(name: "Group A Streptococcus (Parents/Caregivers)", contagious: true)
   all_diseases << Disease.new(name: "Harmful Algal Blooms", contagious: false)
   all_diseases << Disease.new(name: "Headaches", contagious: true)
   all_diseases << Disease.new(name: "Heat-related Illnesses", contagious: true)
   all_diseases << Disease.new(name: "Hepatitis", contagious: false)
   all_diseases << Disease.new(name: "Histoplasmosis", contagious: true)
   all_diseases << Disease.new(name: "Human Metapneumovirus", contagious: false)
   all_diseases << Disease.new(name: "Incontinence", contagious: true)
   all_diseases << Disease.new(name: "Lead Poisoning", contagious: false)
   all_diseases << Disease.new(name: "Leptospirosis", contagious: true)
   all_diseases << Disease.new(name: "Lupus", contagious: false)
   all_diseases << Disease.new(name: "Lymphogranuloma Venereum (LGV)", contagious: true)
   all_diseases << Disease.new(name: "Influenza", contagious: false)
   all_diseases << Disease.new(name: "Legionnaires' Disease", contagious: true)
   all_diseases << Disease.new(name: "Listeriosis", contagious: false)
   all_diseases << Disease.new(name: "Lyme Disease", contagious: true)
   all_diseases << Disease.new(name: "Meningitis", contagious: false)
   all_diseases << Disease.new(name: "Meningococcal Disease", contagious: true)
   all_diseases << Disease.new(name: "MRSA (Pet Owners)", contagious: false)
   all_diseases << Disease.new(name: "Molluscum Contagiosum", contagious: true)
   all_diseases << Disease.new(name: "Neonatal Abstinence Syndrome", contagious: true)
   all_diseases << Disease.new(name: "Non-Gonococcal Urethritis (NGU)", contagious: false)
   all_diseases << Disease.new(name: "Norwalk Virus", contagious: true)
   all_diseases << Disease.new(name: "Pertussis", contagious: false)
   all_diseases << Disease.new(name: "Pneumococcal Disease", contagious: true)
   all_diseases << Disease.new(name: "Primary Amebic Meningoencephalitis", contagious: false)
   all_diseases << Disease.new(name: "Measles", contagious: true)
   all_diseases << Disease.new(name: "MRSA", contagious: false)
   all_diseases << Disease.new(name: "Methyl Parathion", contagious: true)
   all_diseases << Disease.new(name: "Mumps", contagious: false)
   all_diseases << Disease.new(name: "Naegleria Fowleri", contagious: true)
   all_diseases << Disease.new(name: "Noroviruses", contagious: false)
   all_diseases << Disease.new(name: "Pelvic Inflammatory Disease (PID)", contagious: true)
   all_diseases << Disease.new(name: "Plague", contagious: false)
   all_diseases << Disease.new(name: "Polio", contagious: true)
   all_diseases << Disease.new(name: "Parkinson's Disease", contagious: false)
   all_diseases << Disease.new(name: "Rabies", contagious: true)
   all_diseases << Disease.new(name: "Rocky Mountain Spotted Fever", contagious: false)
   all_diseases << Disease.new(name: "Rubella", contagious: true)
   all_diseases << Disease.new(name: "Sarcoidosis", contagious: false)
   all_diseases << Disease.new(name: "SARS (Healthcare Providers)", contagious: true)
   all_diseases << Disease.new(name: "Seoul Virus", contagious: false)
   all_diseases << Disease.new(name: "Shigellosis", contagious: true)
   all_diseases << Disease.new(name: "Stress", contagious: false)
   all_diseases << Disease.new(name: "Sudden Infant Death Syndrome (SIDS)", contagious: true)
   all_diseases << Disease.new(name: "Tetanus", contagious: false)
   all_diseases << Disease.new(name: "Tuberculosis (TB)", contagious: true)
   all_diseases << Disease.new(name: "Respiratory Illness Due to Enterovirus", contagious: false)
   all_diseases << Disease.new(name: "Rotavirus", contagious: true)
   all_diseases << Disease.new(name: "Salmonella", contagious: false)
   all_diseases << Disease.new(name: "SARS", contagious: true)
   all_diseases << Disease.new(name: "Scabies", contagious: true)
   all_diseases << Disease.new(name: "Sexually Transmitted Diseases (STDs)", contagious: false)
   all_diseases << Disease.new(name: "Staph Infection", contagious: true)
   all_diseases << Disease.new(name: "Stroke", contagious: false)
   all_diseases << Disease.new(name: "Syphilis", contagious: true)
   all_diseases << Disease.new(name: "Trichomoniasis", contagious: false)
   all_diseases << Disease.new(name: "Tularemia", contagious: true)
   all_diseases << Disease.new(name: "Vaginitis", contagious: false)
   all_diseases << Disease.new(name: "Wilson's Disease", contagious: true)
   all_diseases << Disease.new(name: "Zika Virus", contagious: false)
   all_diseases << Disease.new(name: "West Nile Virus", contagious: true)
   all_diseases << Disease.new(name: "Yellow Fever", contagious: false)
   all_diseases << Disease.new(name: "Epilepsy", contagious: true)
   all_diseases << Disease.new(name: "Congential heart disease", contagious: false)
   all_diseases << Disease.new(name: "Coronary heart disease", contagious: true)
   all_diseases << Disease.new(name: "Cardiomyopathy", contagious: false)
   all_diseases << Disease.new(name: "Pericarditis", contagious: true)
   all_diseases << Disease.new(name: "Peripheral vascular disease", contagious: true)
   all_diseases << Disease.new(name: "Rheumatic heart disease", contagious: false)
   all_diseases << Disease.new(name: "Aortic valve stenosis", contagious: true)
   all_diseases << Disease.new(name: "Congestive heart failure", contagious: false)
   all_diseases << Disease.new(name: "Atrial fibrillation", contagious: true)
   all_diseases << Disease.new(name: "Fatty liver", contagious: false)
   all_diseases << Disease.new(name: "Hepatitis A", contagious:true)
   all_diseases << Disease.new(name: "Hepatitis B", contagious: true)
   all_diseases << Disease.new(name: "Hepatitis C", contagious: false)
   all_diseases << Disease.new(name: "Hepatitis E", contagious: true)
   all_diseases << Disease.new(name: "Non alcoholic fatty liver disease", contagious: false)
   all_diseases << Disease.new(name: "Cirrhosis", contagious: true)
   all_diseases << Disease.new(name: "Chronic kidney disease", contagious: false)
   all_diseases << Disease.new(name: "Gallstones", contagious: true)
   all_diseases << Disease.new(name: "Kidney infection/Pyelonephritis", contagious: false)
   all_diseases << Disease.new(name: "Kidney stones", contagious: true)
   all_diseases << Disease.new(name: "Kidney failure", contagious: false)
   all_diseases << Disease.new(name: "Polycystic kidney disease", contagious: true)
   all_diseases << Disease.new(name: "Diabetic Nephropathy", contagious: false)
   all_diseases << Disease.new(name: "Nephrotic syndrome", contagious: true)
   all_diseases << Disease.new(name: "Glomerulonephritis", contagious: false)
   all_diseases << Disease.new(name: "Brain aneurysm", contagious: true)
   all_diseases << Disease.new(name: "Bipolar disorder", contagious: true)
   all_diseases << Disease.new(name: "Dementia", contagious: false)
   all_diseases << Disease.new(name: "Schizophrenia", contagious: true)

   Disease.import all_diseases
end