def create_hospital 
   Hospital.create(name: "Cairo Hospital 1", governorate_id: Governorate.find_by_name('Cairo').id)
   Hospital.create(name: "Alexandria Hospital 1", governorate_id: Governorate.find_by_name('Alexandria').id)
   Hospital.create(name: "Giza Hospital 1", governorate_id: Governorate.find_by_name('Giza').id)
   Hospital.create(name: "Shubra el-Khema Hospital 1", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Port Said Hospital 1", governorate_id: Governorate.find_by_name('Por Said').id)
   Hospital.create(name: "Suez Hospital 1", governorate_id: Governorate.find_by_name('Suez').id)
   Hospital.create(name: "El Mahalla el Kubra Hospital 1", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "El Mansoura Hospital 1", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Tanta Hospital 1", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "Asyut Hospital 1", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Fayoum Hospital 1", governorate_id: Governorate.find_by_name('Fayoum').id)
   Hospital.create(name: "Zagazig Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Ismailia Hospital 1", governorate_id: Governorate.find_by_name('Ismailia').id)
   Hospital.create(name: "Khusus Hospital 1", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Aswan Hospital 1", governorate_id: Governorate.find_by_name('Aswan').id)
   Hospital.create(name: "Damanhur Hospital 1", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "El-Minya Hospital 1", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Damietta Hospital 1", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Luxor Hospital 1", governorate_id: Governorate.find_by_name('Luxor').id)
   Hospital.create(name: "Qena Hospital 1", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Beni Suef Hospital 1", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Sohag Hospital 1", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Shibin el-Kom Hospital 1", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Hurghada Hospital 1", governorate_id: Governorate.find_by_name('Albahr Alahmar').id)
   Hospital.create(name: "Banha Hospital 1", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Kafr al-Sheikh Hospital 1", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "Mallawi Hospital 1", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "El Arish Hospital 1", governorate_id: Governorate.find_by_name('North Sinai').id)
   Hospital.create(name: "Belbeis Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "10th of Ramadan City Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Marsa Matruh Hospital 1", governorate_id: Governorate.find_by_name('Matruh').id)
   Hospital.create(name: "Mit Ghamr Hospital 1", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Kafr el-Dawwar Hospital 1", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Qalyub Hospital 1", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Desouk Hospital 1", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "Abu Kabir Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Girga Hospital 1", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Akhmim Hospital 1", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "El-Matareya Hospital 1", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Edko Hospital 1", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Bilqas Hospital 1", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Zifta Hospital 1", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "Samalut Hospital 1", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Menouf Hospital 1", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Senbellawein Hospital 1", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Tahta Hospital 1", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Bush Hospital 1", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Ashmoun Hospital 1", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Manfalut Hospital 1", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Senuris Hospital 1", governorate_id: Governorate.find_by_name('Fayoum').id)
   Hospital.create(name: "Beni Mazar Hospital 1", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Faqous Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Talkha Hospital 1", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Armant Hospital 1", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Maghagha Hospital 1", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Manzala Hospital 1", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Dairut Hospital 1", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Kom Ombo Hospital 1", governorate_id: Governorate.find_by_name('Aswan').id)
   Hospital.create(name: "Kafr al-Zayat Hospital 1", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "Abu Tig Hospital 1", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Qis Hospital 1", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Edfu Hospital 1", governorate_id: Governorate.find_by_name('Aswan').id)
   Hospital.create(name: "Rosetta Hospital 1", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Esna Hospital 1", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Dikirnis Hospital 1", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Abnub Hospital 1", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Tima Hospital 1", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Beila Hospital 1", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "El-Kanater al-Khiria Hospital 1", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Al-Fashn Hospital 1", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Al-Mansha Hospital 1", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Al-Kareen Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "El-Gamalia Hospital 1", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Fuwa Hospital 1", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "Minya al-Qamh Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Kharga Hospital 1", governorate_id: Governorate.find_by_name('Alwadi Aljadid').id)
   Hospital.create(name: "Qus Hospital 1", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Khanka Hospital 1", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Abu Qirqas Hospital 1", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Biba Hospital 1", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Samannoud Hospital 1", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "Minyet al-Nasr Hospital 1", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Shibin al-Qanater Hospital 1", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Ibshawai Hospital 1", governorate_id: Governorate.find_by_name('Fayoum').id)
   Hospital.create(name: "Sherbin Hospital 1", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Darb Nigm Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Basyoun Hospital 1", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "Sers el-Lyan Hospital 1", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Dishna Hospital 1", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Al-Hamool Hospital 1", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "Farshut Hospital 1", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Tala Hospital 1", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Ash-Shuhada Hospital 1", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Tamiya Hospital 1", governorate_id: Governorate.find_by_name('Fayoum').id)
   Hospital.create(name: "Mashtul el-Sook Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Sadat City Hospital 1", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "El-Ghanayem Hospital 1", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Itsa Hospital 1", governorate_id: Governorate.find_by_name('Fayoum').id)
   Hospital.create(name: "Al-Baliyana Hospital 1", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Hosh Issa Hospital 1", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Matai Hospital 1", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Juhayna Hospital 1", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Sidi Salem Hospital 1", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "Naj Hammadi Hospital 1", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Quesna Hospital 1", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Hehya Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Abul Matamir Hospital 1", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "El Ubour Hospital 1", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "El-Badari Hospital 1", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Al-Kanayat Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "At-Tall al-Kabir Hospital 1", governorate_id: Governorate.find_by_name('Ismailia').id)
   Hospital.create(name: "El-Delengat Hospital 1", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Al-Hammam Hospital 1", governorate_id: Governorate.find_by_name('Matruh').id)
   Hospital.create(name: "Tukh Hospital 1", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Bagour Hospital 1", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Etay el-Barud Hospital 1", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Deir Mawas Hospital 1", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Baltim Hospital 1", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "Abu Hammad Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Abu Hummus Hospital 1", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Nabaroh Hospital 1", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Sharm el-Sheikh Hospital 1", governorate_id: Governorate.find_by_name('South of Sinaa').id)
   Hospital.create(name: "Daraw Hospital 1", governorate_id: Governorate.find_by_name('Aswan').id)
   Hospital.create(name: "Al-Maragha Hospital 1", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Sumusta al-Waqf Hospital 1", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Al-Wasta Hospital 1", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Ihnasiya Hospital 1", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Kom Hamadah Hospital 1", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Al-Quseir Hospital 1", governorate_id: Governorate.find_by_name('Albahr Alahmar').id)
   Hospital.create(name: "Qallin Hospital 1", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "Birkat al-Sab Hospital 1", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Safaga Hospital 1", governorate_id: Governorate.find_by_name('Albahr Alahmar').id)
   Hospital.create(name: "Ezbet el-Borg Hospital 1", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Faraskur Hospital 1", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Al-Ibrahimiya Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "El-Santa Hospital 1", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "Ras Gharib Hospital 1", governorate_id: Governorate.find_by_name('Albahr Alahmar').id)
   Hospital.create(name: "Sahel Selim Hospital 1", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Dar as-Salam Hospital 1", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Rafah Hospital 1", governorate_id: Governorate.find_by_name('North Sinai').id)
   Hospital.create(name: "Mit Salsil Hospital 1", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Al-Husseinieh Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Kafr el-Batikh Hospital 1", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Kafr Saqr Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Bani Ubayd Hospital 1", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "El-Qantara Hospital 1", governorate_id: Governorate.find_by_name('Ismailia').id)
   Hospital.create(name: "Metoubes Hospital 1", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "El-Rahmaniyah Hospital 1", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Shubrakhit Hospital 1", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "El-Mahmoudiyah Hospital 1", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Al-Waqf Hospital 1", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "New Damietta Hospital 1", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Qaha Hospital 1", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Kotoor Hospital 1", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "Abu Suweir-el-Mahatta Hospital 1", governorate_id: Governorate.find_by_name('Ismailia').id)
   Hospital.create(name: "Kafr Shukr Hospital 1", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Kafr Saad Hospital 1", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Qift Hospital 1", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Fayed Hospital 1", governorate_id: Governorate.find_by_name('Ismailia').id)
   Hospital.create(name: "Saqultah Hospital 1", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Wadi al-Natrun Hospital 1", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Naqadah Hospital 1", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "As-Sarw Hospital 1", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Awlad Saqr Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Sidi Barrani Hospital 1", governorate_id: Governorate.find_by_name('Matruh').id)
   Hospital.create(name: "Al-Basaliyah Bahri Hospital 1", governorate_id: Governorate.find_by_name('Aswan').id)
   Hospital.create(name: "Badr Hospital 1", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Sedfa Hospital 1", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "El-Qantara ash-Sharqiya Hospital 1", governorate_id: Governorate.find_by_name('Ismailia').id)
   Hospital.create(name: "Ar-Ruda Hospital 1", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Mut Hospital 1", governorate_id: Governorate.find_by_name('Alwadi Aljadid').id)
   Hospital.create(name: "Al-Tur Hospital 1", governorate_id: Governorate.find_by_name('South of Sinaa').id)
   Hospital.create(name: "New Salhia Hospital 1", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Ash-Shaykh Zawid Hospital 1", governorate_id: Governorate.find_by_name('North Sinai').id)
   Hospital.create(name: "Riyadh Hospital 1", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "New Beni Suef Hospital 1", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Aga Hospital 1", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Ad-Dabah Hospital 1", governorate_id: Governorate.find_by_name('Matruh').id)
   Hospital.create(name: "Al-Zarqa Hospital 1", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "As-Sibaiyah Gharb Hospital 1", governorate_id: Governorate.find_by_name('Aswan').id)
   Hospital.create(name: "Siwa Hospital 1", governorate_id: Governorate.find_by_name('Matruh').id)
   Hospital.create(name: "El-Idwa Hospital 1", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Yusuf as-Siddiq Hospital 1", governorate_id: Governorate.find_by_name('Fayoum').id)
   Hospital.create(name: "Al-Bayadiyah Hospital 1", governorate_id: Governorate.find_by_name('Luxor').id)
   Hospital.create(name: "Cairo Hospital 2", governorate_id: Governorate.find_by_name('Cairo').id)
   Hospital.create(name: "Alexandria Hospital 2", governorate_id: Governorate.find_by_name('Alexandria').id)
   Hospital.create(name: "Giza Hospital 2", governorate_id: Governorate.find_by_name('Giza').id)
   Hospital.create(name: "Shubra el-Khema Hospital 2", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Port Said Hospital 2", governorate_id: Governorate.find_by_name('Por Said').id)
   Hospital.create(name: "Suez Hospital 2", governorate_id: Governorate.find_by_name('Suez').id)
   Hospital.create(name: "El Mahalla el Kubra Hospital 2", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "El Mansoura Hospital 2", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Tanta Hospital 2", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "Asyut Hospital 2", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Fayoum Hospital 2", governorate_id: Governorate.find_by_name('Fayoum').id)
   Hospital.create(name: "Zagazig Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Ismailia Hospital 2", governorate_id: Governorate.find_by_name('Ismailia').id)
   Hospital.create(name: "Khusus Hospital 2", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Aswan Hospital 2", governorate_id: Governorate.find_by_name('Aswan').id)
   Hospital.create(name: "Damanhur Hospital 2", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "El-Minya Hospital 2", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Damietta Hospital 2", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Luxor Hospital 2", governorate_id: Governorate.find_by_name('Luxor').id)
   Hospital.create(name: "Qena Hospital 2", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Beni Suef Hospital 2", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Sohag Hospital 2", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Shibin el-Kom Hospital 2", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Hurghada Hospital 2", governorate_id: Governorate.find_by_name('Albahr Alahmar').id)
   Hospital.create(name: "Banha Hospital 2", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Kafr al-Sheikh Hospital 2", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "Mallawi Hospital 2", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "El Arish Hospital 2", governorate_id: Governorate.find_by_name('North Sinai').id)
   Hospital.create(name: "Belbeis Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "20th of Ramadan City Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Marsa Matruh Hospital 2", governorate_id: Governorate.find_by_name('Matruh').id)
   Hospital.create(name: "Mit Ghamr Hospital 2", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Kafr el-Dawwar Hospital 2", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Qalyub Hospital 2", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Desouk Hospital 2", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "Abu Kabir Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Girga Hospital 2", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Akhmim Hospital 2", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "El-Matareya Hospital 2", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Edko Hospital 2", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Bilqas Hospital 2", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Zifta Hospital 2", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "Samalut Hospital 2", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Menouf Hospital 2", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Senbellawein Hospital 2", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Tahta Hospital 2", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Bush Hospital 2", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Ashmoun Hospital 2", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Manfalut Hospital 2", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Senuris Hospital 2", governorate_id: Governorate.find_by_name('Fayoum').id)
   Hospital.create(name: "Beni Mazar Hospital 2", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Faqous Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Talkha Hospital 2", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Armant Hospital 2", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Maghagha Hospital 2", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Manzala Hospital 2", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Dairut Hospital 2", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Kom Ombo Hospital 2", governorate_id: Governorate.find_by_name('Aswan').id)
   Hospital.create(name: "Kafr al-Zayat Hospital 2", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "Abu Tig Hospital 2", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Qis Hospital 2", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Edfu Hospital 2", governorate_id: Governorate.find_by_name('Aswan').id)
   Hospital.create(name: "Rosetta Hospital 2", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Esna Hospital 2", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Dikirnis Hospital 2", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Abnub Hospital 2", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Tima Hospital 2", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Beila Hospital 2", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "El-Kanater al-Khiria Hospital 2", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Al-Fashn Hospital 2", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Al-Mansha Hospital 2", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Al-Kareen Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "El-Gamalia Hospital 2", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Fuwa Hospital 2", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "Minya al-Qamh Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Kharga Hospital 2", governorate_id: Governorate.find_by_name('Alwadi Aljadid').id)
   Hospital.create(name: "Qus Hospital 2", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Khanka Hospital 2", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Abu Qirqas Hospital 2", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Biba Hospital 2", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Samannoud Hospital 2", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "Minyet al-Nasr Hospital 2", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Shibin al-Qanater Hospital 2", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Ibshawai Hospital 2", governorate_id: Governorate.find_by_name('Fayoum').id)
   Hospital.create(name: "Sherbin Hospital 2", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Darb Nigm Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Basyoun Hospital 2", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "Sers el-Lyan Hospital 2", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Dishna Hospital 2", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Al-Hamool Hospital 2", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "Farshut Hospital 2", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Tala Hospital 2", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Ash-Shuhada Hospital 2", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Tamiya Hospital 2", governorate_id: Governorate.find_by_name('Fayoum').id)
   Hospital.create(name: "Mashtul el-Sook Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Sadat City Hospital 2", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "El-Ghanayem Hospital 2", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Itsa Hospital 2", governorate_id: Governorate.find_by_name('Fayoum').id)
   Hospital.create(name: "Al-Baliyana Hospital 2", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Hosh Issa Hospital 2", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Matai Hospital 2", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Juhayna Hospital 2", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Sidi Salem Hospital 2", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "Naj Hammadi Hospital 2", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Quesna Hospital 2", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Hehya Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Abul Matamir Hospital 2", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "El Ubour Hospital 2", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "El-Badari Hospital 2", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Al-Kanayat Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "At-Tall al-Kabir Hospital 2", governorate_id: Governorate.find_by_name('Ismailia').id)
   Hospital.create(name: "El-Delengat Hospital 2", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Al-Hammam Hospital 2", governorate_id: Governorate.find_by_name('Matruh').id)
   Hospital.create(name: "Tukh Hospital 2", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Bagour Hospital 2", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Etay el-Barud Hospital 2", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Deir Mawas Hospital 2", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Baltim Hospital 2", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "Abu Hammad Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Abu Hummus Hospital 2", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Nabaroh Hospital 2", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Sharm el-Sheikh Hospital 2", governorate_id: Governorate.find_by_name('South of Sinaa').id)
   Hospital.create(name: "Daraw Hospital 2", governorate_id: Governorate.find_by_name('Aswan').id)
   Hospital.create(name: "Al-Maragha Hospital 2", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Sumusta al-Waqf Hospital 2", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Al-Wasta Hospital 2", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Ihnasiya Hospital 2", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Kom Hamadah Hospital 2", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Al-Quseir Hospital 2", governorate_id: Governorate.find_by_name('Albahr Alahmar').id)
   Hospital.create(name: "Qallin Hospital 2", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "Birkat al-Sab Hospital 2", governorate_id: Governorate.find_by_name('Menoufia').id)
   Hospital.create(name: "Safaga Hospital 2", governorate_id: Governorate.find_by_name('Albahr Alahmar').id)
   Hospital.create(name: "Ezbet el-Borg Hospital 2", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Faraskur Hospital 2", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Al-Ibrahimiya Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "El-Santa Hospital 2", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "Ras Gharib Hospital 2", governorate_id: Governorate.find_by_name('Albahr Alahmar').id)
   Hospital.create(name: "Sahel Selim Hospital 2", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "Dar as-Salam Hospital 2", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Rafah Hospital 2", governorate_id: Governorate.find_by_name('North Sinai').id)
   Hospital.create(name: "Mit Salsil Hospital 2", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Al-Husseinieh Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Kafr el-Batikh Hospital 2", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Kafr Saqr Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Bani Ubayd Hospital 2", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "El-Qantara Hospital 2", governorate_id: Governorate.find_by_name('Ismailia').id)
   Hospital.create(name: "Metoubes Hospital 2", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "El-Rahmaniyah Hospital 2", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Shubrakhit Hospital 2", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "El-Mahmoudiyah Hospital 2", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Al-Waqf Hospital 2", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "New Damietta Hospital 2", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Qaha Hospital 2", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Kotoor Hospital 2", governorate_id: Governorate.find_by_name('Algharbia').id)
   Hospital.create(name: "Abu Suweir-el-Mahatta Hospital 2", governorate_id: Governorate.find_by_name('Ismailia').id)
   Hospital.create(name: "Kafr Shukr Hospital 2", governorate_id: Governorate.find_by_name('Qalyubia').id)
   Hospital.create(name: "Kafr Saad Hospital 2", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Qift Hospital 2", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "Fayed Hospital 2", governorate_id: Governorate.find_by_name('Ismailia').id)
   Hospital.create(name: "Saqultah Hospital 2", governorate_id: Governorate.find_by_name('Sohag').id)
   Hospital.create(name: "Wadi al-Natrun Hospital 2", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Naqadah Hospital 2", governorate_id: Governorate.find_by_name('Qana').id)
   Hospital.create(name: "As-Sarw Hospital 2", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Awlad Saqr Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Sidi Barrani Hospital 2", governorate_id: Governorate.find_by_name('Matruh').id)
   Hospital.create(name: "Al-Basaliyah Bahri Hospital 2", governorate_id: Governorate.find_by_name('Aswan').id)
   Hospital.create(name: "Badr Hospital 2", governorate_id: Governorate.find_by_name('Albuhayra').id)
   Hospital.create(name: "Sedfa Hospital 2", governorate_id: Governorate.find_by_name('Asyut').id)
   Hospital.create(name: "El-Qantara ash-Sharqiya Hospital 2", governorate_id: Governorate.find_by_name('Ismailia').id)
   Hospital.create(name: "Ar-Ruda Hospital 2", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "Mut Hospital 2", governorate_id: Governorate.find_by_name('Alwadi Aljadid').id)
   Hospital.create(name: "Al-Tur Hospital 2", governorate_id: Governorate.find_by_name('South of Sinaa').id)
   Hospital.create(name: "New Salhia Hospital 2", governorate_id: Governorate.find_by_name('Alsharqia').id)
   Hospital.create(name: "Ash-Shaykh Zawid Hospital 2", governorate_id: Governorate.find_by_name('North Sinai').id)
   Hospital.create(name: "Riyadh Hospital 2", governorate_id: Governorate.find_by_name('Kafr El-Sheikh').id)
   Hospital.create(name: "New Beni Suef Hospital 2", governorate_id: Governorate.find_by_name('Bani Sweif').id)
   Hospital.create(name: "Aga Hospital 2", governorate_id: Governorate.find_by_name('Dakahlia').id)
   Hospital.create(name: "Ad-Dabah Hospital 2", governorate_id: Governorate.find_by_name('Matruh').id)
   Hospital.create(name: "Al-Zarqa Hospital 2", governorate_id: Governorate.find_by_name('Damietta').id)
   Hospital.create(name: "As-Sibaiyah Gharb Hospital 2", governorate_id: Governorate.find_by_name('Aswan').id)
   Hospital.create(name: "Siwa Hospital 2", governorate_id: Governorate.find_by_name('Matruh').id)
   Hospital.create(name: "El-Idwa Hospital 2", governorate_id: Governorate.find_by_name('minya').id)
   Hospital.create(name: "Yusuf as-Siddiq Hospital 2", governorate_id: Governorate.find_by_name('Fayoum').id)
   Hospital.create(name: "Al-Bayadiyah Hospital 2", governorate_id: Governorate.find_by_name('Luxor').id)
end